#默认使用配置
spring:
  profiles:
    active: test

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.msbkj.entity
  mapperLocations: classpath:mapper/*.xml

  spring:
    thymeleaf:
      prefix: classpath:/templates/
      cache: false

#日志配置
logging:
  level:
    com.msbkj.mapper: debug

---

#开发配置
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://localhost:3306/datingsites?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
